### ISSUE TITLE
AttributeError: 'Interaction' object has no attribute 'edit_original_message' with paginator type=2

### ISSUE THREAD

**Issue by not-Karot** [Tommodev-06/pycord-paging#2]
When using paginator of type 2 if you press on a button it returns 
`AttributeError: 'Interaction' object has no attribute 'edit_original_message'`.

My code is the default one found in the README.

`
from discord import Embed
from discord.ext import commands
from paginator import Paginator, Page

bot = commands.Bot(command_prefix="!")
paginator = Paginator(bot)

@bot.event
async def on_ready():
    print("Bot online")

@bot.command()
async def paginator(ctx):
    pages = [
        Page(embed=Embed(title="Page #1", description="Testing")),
        Page(embed=Embed(title="Page #2", description="Still testing")),
        Page(embed=Embed(title="Page #3", description="Guess... testing"))
    ]

    await paginator.send(ctx.channel, pages, type=2, author=ctx.author, disable_on_timeout=False)

bot.run("...")
`
  
I'm using 
```
discord=1.7.3  
discord-py=2.0.0
```
I guess the problem should be with the update of the discord library, can you please look at that and make it work for the updated library?
Thanks

**Comment by Tommodev-06** [comment]
Hello!

The package works with Pycord, so it doesn't work with discord.py. 
I have planned anyway to make the library works with discord.py, but I will take time since my PC is broken and in the latest days I am busy with personal things.

Tom
